name: Faster Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Run Playwright tests
      uses: docker://mcr.microsoft.com/playwright:v1.55.0-jammy
      with:
        args: npx playwright test
