name: Faster Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Run Playwright tests
      uses: docker://mcr.microsoft.com/playwright:v1.34.3-jammy
      with:
        args: npx playwright test
